#!/bin/sh
set -ex

TIME=1s

go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateAdd2$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollAdd2$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesAdd2$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateAdd$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollAdd$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesAdd$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateAssign$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollAssign$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesAssign$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateDefine$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollDefine$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesDefine$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateIf2$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollIf2$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesIf2$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateIf3$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollIf3$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesIf3$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateIf4$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollIf4$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesIf4$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateIf5$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollIf5$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesIf5$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateIf$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollIf$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesIf$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateNest$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollNest$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesNest$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateReturn$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollReturn$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesReturn$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateFor$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollFor$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesFor$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzTranslateFor2$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzUnrollFor2$"
go test ./fuzz -fuzztime ${TIME} -fuzz="^FuzzRmBranchesFor2$"
